title: Mischa Batelaan
author: Mischa Batelaan
subtitle: personal site

# url: "http://mischabatelaan.com"
url: "https://mbatelaan.github.io"
baseurl: ""
blogurl: "/blog"

footer_only_homepage: true
# footer_url: "https://github.com/rahul-bothra"
# footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.webp
favicon_location: assets/favicon.ico

permalink: /blog/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Blog"
   link: "blog"
 - name: "Tags"
   link: "tags"
 # - name: "Resume"
 #   absolute-link: "https://rahul-bothra.github.io/CV.pdf"
